# Generated by Django 5.0.4 on 2024-09-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('account_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=10)),
            ],
        ),
    ]
