# Generated by Django 5.0.4 on 2024-09-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_customuser_role_alter_transaction_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
