# Generated by Django 5.0.4 on 2024-10-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        
    ]
