# Generated by Django 5.0.4 on 2024-10-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_customer_password_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('Top', 'Top')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('years_of_experience', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
    ]
