# Generated by Django 5.0.4 on 2024-10-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_customer_failed_attempts_customer_is_locked_and_more'),
    ]


