# Generated by Django 5.0.4 on 2024-10-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
